[package]
name = "adfly-skip"
version = "0.1.0"
authors = ["belohnung <belohnung@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.24"
base64 = "0.11.0"